controller_list:
  - name: fake_susan_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7
initial:  # Define initial robot poses per group
  - group: susan_arm_group
    pose: zero_position